include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = SideButtonActionsPrefs
SideButtonActionsPrefs_FILES = SBASettingsController.m
SideButtonActionsPrefs_FRAMEWORKS = UIKit
SideButtonActionsPrefs_PRIVATE_FRAMEWORKS = Preferences
SideButtonActionsPrefs_INSTALL_PATH = /Library/PreferenceBundles
SideButtonActionsPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
