#!/bin/sh
if [ "$1" = "configure" ]; then
    launchctl unload /Library/LaunchDaemons/com.chr1s.tapflashd.plist >/dev/null 2>&1 || true
    launchctl load /Library/LaunchDaemons/com.chr1s.tapflashd.plist >/dev/null 2>&1 || true
fi
exit 0
